package gui_swing.ui.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class LoginFrame extends JFrame {

    public static final int HEIGHT = 500;
    public static final int WIDTH = 650;


    public LoginFrame() {

        setSize(WIDTH, HEIGHT);
        setContentPane(mainPanel);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        mainPanel.getRootPane().setDefaultButton(loginButton);


    }

    private JPanel mainPanel;
    private JPanel loginTopPanel;
    private JPanel loginStatusPanel;
    private JPanel loginRightPanel;
    private JTextField loginTextField;
    private JPasswordField loginPasswordField;
    private JLabel loginLabel;
    private JLabel passwordLabel;
    private JLabel imageLabel;
    private JButton loginButton;
    private JButton exitButton;
    private JLabel statusLabel;

    public JPanel getButtonsPanel() {
        return buttonsPanel;
    }

    public void setButtonsPanel(JPanel buttonsPanel) {
        this.buttonsPanel = buttonsPanel;
    }

    private JPanel buttonsPanel;
    private JPanel deadPanel;


    public JLabel getStatusLabel() {
        return statusLabel;
    }


    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JPanel getLoginTopPanel() {
        return loginTopPanel;
    }

    public JPanel getLoginStatusPanel() {
        return loginStatusPanel;
    }

    public JPanel getLoginRightPanel() {
        return loginRightPanel;
    }

    public JTextField getLoginTextField() {
        return loginTextField;
    }

    public JPasswordField getLoginPasswordField() {
        return loginPasswordField;
    }

    public JLabel getLoginLabel() {
        return loginLabel;
    }

    public JLabel getPasswordLabel() {
        return passwordLabel;
    }

    public JLabel getImageLabel() {
        return imageLabel;
    }

    public JButton getLoginButton() {
        return loginButton;
    }

    public JButton getExitButton() {
        return exitButton;
    }


    private void createUIComponents() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-9589762));
        mainPanel.setName("mainPanel");
        mainPanel.setOpaque(true);
        loginTopPanel = new JPanel();
        loginTopPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        loginTopPanel.setBackground(new Color(-9589762));
        loginTopPanel.setForeground(new Color(-14802385));
        loginTopPanel.setOpaque(true);
        mainPanel.add(loginTopPanel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        imageLabel = new JLabel();
        imageLabel.setIcon(new ImageIcon(getClass().getResource("/img/Logo-BK.png")));
        imageLabel.setText("");
        loginTopPanel.add(imageLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginStatusPanel = new JPanel();
        loginStatusPanel.setLayout(new BorderLayout(0, 0));
        loginStatusPanel.setAutoscrolls(true);
        loginStatusPanel.setBackground(new Color(-9589762));
        loginStatusPanel.setOpaque(true);
        loginTopPanel.add(loginStatusPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, new Dimension(600, -1), 0, false));
        statusLabel = new JLabel();
        statusLabel.setAlignmentX(0.0f);
        statusLabel.setAlignmentY(0.0f);
        statusLabel.setAutoscrolls(false);
        statusLabel.setBackground(new Color(-9589762));
        statusLabel.setHorizontalAlignment(2);
        statusLabel.setHorizontalTextPosition(2);
        statusLabel.setText("");
        statusLabel.putClientProperty("html.disable", Boolean.FALSE);
        loginStatusPanel.add(statusLabel, BorderLayout.CENTER);
        loginRightPanel = new JPanel();
        loginRightPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), 5, 5));
        loginRightPanel.setBackground(new Color(-9589762));
        loginRightPanel.setEnabled(true);
        loginRightPanel.setForeground(new Color(-14802385));
        loginRightPanel.setOpaque(true);
        mainPanel.add(loginRightPanel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        loginTextField = new JTextField();
        loginTextField.setBackground(new Color(-12748334));
        loginTextField.setForeground(new Color(-1));
        loginRightPanel.add(loginTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), new Dimension(250, -1), null, 0, false));
        buttonsPanel = new JPanel();
        buttonsPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 5, 5));
        buttonsPanel.setBackground(new Color(-9589762));
        buttonsPanel.setForeground(new Color(-14802385));
        buttonsPanel.setOpaque(true);
        loginRightPanel.add(buttonsPanel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, true));
        buttonsPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-9589762)));
        exitButton = new JButton();
        exitButton.setBackground(new Color(-12748334));
        exitButton.setBorderPainted(false);
        exitButton.setDoubleBuffered(false);
        exitButton.setForeground(new Color(-14802385));
        exitButton.setHideActionText(true);
        exitButton.setMargin(new Insets(0, 0, 0, 0));
        exitButton.setText("Zamknij");
        exitButton.putClientProperty("hideActionText", Boolean.TRUE);
        buttonsPanel.add(exitButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginButton = new JButton();
        loginButton.setBackground(new Color(-12748334));
        loginButton.setBorderPainted(false);
        loginButton.setForeground(new Color(-14802385));
        loginButton.setText("Zaloguj");
        buttonsPanel.add(loginButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordLabel = new JLabel();
        passwordLabel.setText("Hasło:");
        loginRightPanel.add(passwordLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginLabel = new JLabel();
        loginLabel.setText("Login:");
        loginRightPanel.add(loginLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginPasswordField = new JPasswordField();
        loginPasswordField.setBackground(new Color(-12748334));
        loginPasswordField.setCaretColor(new Color(-12748334));
        loginPasswordField.setDisabledTextColor(new Color(-7948571));
        loginPasswordField.setForeground(new Color(-1));
        loginRightPanel.add(loginPasswordField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(250, -1), new Dimension(250, -1), null, 0, false));
        deadPanel = new JPanel();
        deadPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        deadPanel.setBackground(new Color(-9589762));
        mainPanel.add(deadPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
